server:
  port: 28080
spring:
  datasource:
    url: jdbc:mysql://www.moyulab.cn:3306/haigelab?useUnicode=true&characterEncoding=utf8
    username: root
    password: devThree123!
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:com/mht/springbootmybatisplus/mapper/xml/*.xml
  type-aliases-package: com.moyulab.haige.haigelab.entity
  configuration:
    map-underscore-to-camel-case: true

#logging:
  #level:
    #com.moyulab: DEBUG
  #path: /logs
  #file: E:/moyulab/logs/haigelab.log


